### ISSUE TITLE
[docker/photon] missing nominatim postgres module on import 

### ISSUE THREAD

**Issue by 3nprob** [ellenhp/headway#16]
I'm noticing that since nominatim is not installed on the (container local) postgres server on the photon import step, the following error is yielded:

```
ERROR:  could not access file "/usr/local/lib/nominatim/module//nominatim.so": No such file or directory
ERROR:  function public.transliteration(text) does not exist
```

Could be resolved by either installing the module inside the photon container, or use a shared postgres server (either independent or the one bundled in the nominatim container)

Or maybe this is a non-issue?

**Comment by ellenhp** [comment]
This is a good catch. Wild idea: what if instead of passing around a postgres pg_dump, we just give the photon container a hostname and port for it to import from? I really don't want to install all of nominatim on the photon image and ideally it wouldn't even have a postgis installation either.

**Comment by ellenhp** [comment]
The makefile for generating the photon index would look something like this:

[create docker network for nominatim->photon import]
docker run --rm -d [nominatim container adding it to the network we just created]
docker run --rm [photon container, adding it to the network and telling it to import from above container]
docker kill [nominatim container]

**Comment by 3nprob** [comment]
> This is a good catch. Wild idea: what if instead of passing around a postgres pg_dump, we just give the photon container a hostname and port for it to import from?

IMO this is the best approach. More efficient, flexible, and (potentially) robust than the explored alternatives.

**Comment by ellenhp** [comment]
I tentatively agree, but I think the frontend needs a lot of work and I still need to hook up more routing modes. The build process isn't really high on my list of concerns after https://github.com/3nprob/headway/pull/1 or some variation of it gets merged back into main. The work you did should unblock productionization because we can take the entire data directory and upload it as a tarball to S3, then have a k8s init container that downloads it and extracts it to a local volume.

**Comment by ellenhp** [comment]
This should be resolved now since the runtime photon image no longer has a postgres database at all.
