### ISSUE TITLE
Add attribution for use of OpenStreetMap data

### ISSUE THREAD

**Issue by donalhunt** [ellenhp/headway#3]
Use of OpenStreetMap data requires attribution to be provided when data from the project is utilised.

See https://www.openstreetmap.org/copyright

**Comment by donalhunt** [comment]
The thread on hackernews suggests it's already there. May need to check different viewports since I don't see it on mobile web (Android/Chrome).

**Comment by ellenhp** [comment]
It should be in the mbtiles that Headway generates, and surfaced by maplibre-gl-js in the lower-right corner of the screen on an LTR layout. Though come to think of it, that icon will be covered up if a POI is selected or in the directions page, so I'll keep this open to track that.

**Comment by ellenhp** [comment]
This should be fixed by https://github.com/ellenhp/headway/commit/3c89bfa8ac71133730afadc94e43e5e394a2f9bd which is currently building on the demo server and should be up momentarily. Also very unrelated but I guess this project is getting "big enough" that I should stop committing directly to main, haha.
